TRAIN:
  ENABLE: True
  # DATASET: imagenet
  BATCH_SIZE: 200 # Per GPU
  EVAL_PERIOD: 100
  CHECKPOINT_PERIOD: 100 
  RESUME: ""
  SAVE_EVERY: 5
WANDB: None
FINETUNE:
  CHKPT: "/home/tyler/xl_mae/ckpts/fin.pth"
  GLOBAL_POOL: True
DATA:
  DATA_PATH: "/home/group/ilsvrc"
  NUM_CLASSES: 1000
  INPUT_SIZE: 224
MODEL: 
  ARCH: "vit_tiny_patch16"
  DROPPATH_RATE: 0.1
# CLS_EMBED_ON: False
#   EMBED_DIM: 384
#   NUM_HEADS: 6
#   MLP_RATIO: 4.0
#   QKV_BIAS: True
#   DEPTH: 12
#   POOL_KV_STRIDE: []
AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m9-mstd0.5-inc1
  SMOOTHING: 0.1
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  EPOCHS: 100
  ACCUM_ITER: 1
  CLIP_GRAD: None
  BASE_LR: 1e-3
  LAYER_DECAY: 0.75
  WEIGHT_DECAY: 0.05
  MIN_LR: 1e-6
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 1e-12
  OPTIMIZING_METHOD: adamw
DATA_LOADER:
  NUM_WORKERS: 10 
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: .